
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:

title: Inspire 1A03
description: McMaster University Spring Term 2020

theme: jekyll-theme-midnight
